{
 "title": "Kubernetes Pods (cpu / memory / IO) by OrgX",
 "description": "Kubernetes Pods (cpu / memory / IO) by OrgX",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "{{ .Release.Namespace }} Namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "cpu_usage_seconds",
   "type": "timeseries",
   "description": "container_cpu_usage_seconds_total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"{{ .Release.Namespace }}\",container!=\"\",container!=\"POD\",container!=\".*tornadoapp-{{ .Values.orgname }}.*\",container!~\".*ca-{{ .Values.orgname }}.*\"}[$__rate_interval])) by (container)",
     "legendFormat": "{{ .Values.legendFormat_Container }}"
    }
   ]
  },
  {
   "title": "cpu throttled",
   "type": "timeseries",
   "description": "container_cpu_cfs_throttled_seconds_total",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{namespace=\"{{ .Release.Namespace }}\",container!=\"\",container!=\"POD\",container!=\".*tornadoapp-{{ .Values.orgname }}.*\",container!~\".*ca-{{ .Values.orgname }}.*\"}[$__rate_interval])) by (container)",
     "legendFormat": "{{ .Values.legendFormat_Container }}"
    }
   ]
  },
  {
   "title": "fs_writes_bytes",
   "type": "timeseries",
   "description": "container_fs_writes_bytes_total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace=\"{{ .Release.Namespace }}\",container=~\".+\",container!~\".*ca-{{ .Values.orgname }}.*\"}[$__rate_interval])) by (container)",
     "legendFormat": "{{ .Values.legendFormat_Container }}"
    }
   ]
  },
  {
   "title": "fs_reads_bytes",
   "type": "timeseries",
   "description": "container_fs_reads_bytes_total",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{namespace=\"{{ .Release.Namespace }}\",container=~\".+\",container!~\".*ca-{{ .Values.orgname }}.*\"}[$__rate_interval])) by (container)",
     "legendFormat": "{{ .Values.legendFormat_Container }}"
    }
   ]
  },
  {
   "title": "network_receive_bytes",
   "type": "timeseries",
   "description": "container_network_receive_bytes_total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"{{ .Release.Namespace }}\",name!~\".*ca-{{ .Values.orgname }}.*\"}[$__rate_interval])) by (name)",
     "legendFormat": "{{ .Values.legendFormat_Name }}"
    }
   ]
  },
  {
   "title": "network_transmit_bytes",
   "type": "timeseries",
   "description": "container_network_transmit_bytes_total",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"{{ .Release.Namespace }}\",name!~\".*ca-{{ .Values.orgname }}.*\"}[$__rate_interval])) by (name)",
     "legendFormat": "{{ .Values.legendFormat_Name }}"
    }
   ]
  },
  {
   "title": "network_errors",
   "type": "timeseries",
   "description": "container_network_receive_errors_total / container_network_transmit_errors_total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_errors_total{namespace=\"{{ .Release.Namespace }}\",name!~\".*ca-{{ .Values.orgname }}.*\"}[$__rate_interval])) by (name)",
     "legendFormat": "{{ .Values.legendFormat_ReceiveName }}"
    },
    {
     "expr": "sum(rate(container_network_transmit_errors_total{namespace=\"{{ .Release.Namespace }}\",name!~\".*ca-{{ .Values.orgname }}.*\"}[$__rate_interval])) by (name)",
     "legendFormat": "{{ .Values.legendFormat_TransmitName }}"
    }
   ]
  },
  {
   "title": "network_packets_dropped",
   "type": "timeseries",
   "description": "container_network_receive_packets_dropped_total",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total{namespace=\"{{ .Release.Namespace }}\",name!~\".*ca-{{ .Values.orgname }}.*\"}[$__rate_interval])) by (name)",
     "legendFormat": "{{ .Values.legendFormat_ReceiveName }}"
    },
    {
     "expr": "sum(rate(container_network_transmit_packets_dropped_total{namespace=\"{{ .Release.Namespace }}\",name!~\".*ca-{{ .Values.orgname }}.*\"}[$__rate_interval])) by (name)",
     "legendFormat": "{{ .Values.legendFormat_TransmitName }}"
    }
   ]
  },
  {
   "title": "memory_working_set_bytes",
   "type": "timeseries",
   "description": "container_memory_working_set_bytes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"{{ .Release.Namespace }}\",name!~\".*POD.*\",name!=\"\",name!~\".*ca-{{ .Values.orgname }}.*\"}) by (name)",
     "legendFormat": "{{ .Values.legendFormat_Name }}"
    }
   ]
  },
  { "title": "default Namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "cpu_usage_seconds",
   "type": "timeseries",
   "description": "container_cpu_usage_seconds_total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"default\",container!=\"\",container!=\"POD\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ .Values.legendFormat_Pod }}"
    }
   ]
  },
  {
   "title": "cpu throttled",
   "type": "timeseries",
   "description": "container_cpu_cfs_throttled_seconds_total",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{namespace=\"default\",container!=\"\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ .Values.legendFormat_Pod }}"
    }
   ]
  },
  {
   "title": "fs_writes_bytes",
   "type": "timeseries",
   "description": "container_fs_writes_bytes_total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace=\"default\",container=~\".+\"}[$__rate_interval])) by (pod,device)",
     "legendFormat": "{{ .Values.legendFormat_Pod }}"
    }
   ]
  },
  {
   "title": "fs_reads_bytes",
   "type": "timeseries",
   "description": "container_fs_reads_bytes_total",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{namespace=\"default\",container=~\".+\"}[$__rate_interval])) by (pod,device)",
     "legendFormat": "{{ .Values.legendFormat_Pod }}"
    }
   ]
  },
  {
   "title": "network_receive_bytes",
   "type": "timeseries",
   "description": "container_network_receive_bytes_total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"default\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ .Values.legendFormat_Pod }}"
    }
   ]
  },
  {
   "title": "network_transmit_bytes",
   "type": "timeseries",
   "description": "container_network_transmit_bytes_total",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"default\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ .Values.legendFormat_Pod }}"
    }
   ]
  },
  {
   "title": "network_errors",
   "type": "timeseries",
   "description": "container_network_receive_errors_total / container_network_transmit_errors_total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_errors_total{namespace=\"default\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ .Values.legendFormat_ReceivePod }}"
    },
    {
     "expr": "sum(rate(container_network_transmit_errors_total{namespace=\"default\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ .Values.legendFormat_TransmitPod }}"
    }
   ]
  },
  {
   "title": "network_packets_dropped",
   "type": "timeseries",
   "description": "container_network_receive_packets_dropped_total / container_network_transmit_packets_dropped_total",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total{namespace=\"default\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ .Values.legendFormat_ReceivePod }}"
    },
    {
     "expr": "sum(rate(container_network_transmit_packets_dropped_total{namespace=\"default\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ .Values.legendFormat_TransmitPod }}"
    }
   ]
  },
  {
   "title": "memory_working_set_bytes",
   "type": "timeseries",
   "description": "container_memory_working_set_bytes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"default\",name!~\".*POD.*\",name!=\"\",name!~\".*configmap.*\"}) by (pod)",
     "legendFormat": "{{ .Values.legendFormat_Pod }}"
    }
   ]
  },
  { "title": "cloudWatch Namesapce", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "cpu_usage_seconds",
   "type": "timeseries",
   "description": "container_cpu_usage_seconds_total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"amazon-cloudwatch\",container!=\"\",container!=\"POD\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ .Values.legendFormat_Pod }}"
    }
   ]
  },
  {
   "title": "cpu throttled",
   "type": "timeseries",
   "description": "container_cpu_cfs_throttled_seconds_total",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{namespace=\"amazon-cloudwatch\"}[$__rate_interval])) by (id)",
     "legendFormat": "{{ .Values.legendFormat_Id }}"
    }
   ]
  },
  {
   "title": "fs_writes_bytes",
   "type": "timeseries",
   "description": "container_fs_writes_bytes_total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace=\"amazon-cloudwatch\",container=~\".+\"}[$__rate_interval])) by (name)",
     "legendFormat": "{{ .Values.legendFormat_Pod }}"
    }
   ]
  },
  {
   "title": "fs_reads_bytes",
   "type": "timeseries",
   "description": "container_fs_reads_bytes_total",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{namespace=\"amazon-cloudwatch\"}[$__rate_interval])) by (id)",
     "legendFormat": "{{ .Values.legendFormat_Pod }}"
    }
   ]
  },
  {
   "title": "network_receive_bytes",
   "type": "timeseries",
   "description": "container_network_receive_bytes_total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"amazon-cloudwatch\"}[$__rate_interval])) by (name)",
     "legendFormat": "{{ .Values.legendFormat_Name }}"
    }
   ]
  },
  {
   "title": "network_transmit_bytes",
   "type": "timeseries",
   "description": "container_network_transmit_bytes_total",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"amazon-cloudwatch\"}[$__rate_interval])) by (name)",
     "legendFormat": "{{ .Values.legendFormat_Name }}"
    }
   ]
  },
  {
   "title": "network_errors",
   "type": "timeseries",
   "description": "container_network_receive_errors_total / container_network_transmit_errors_total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_errors_total{namespace=\"amazon-cloudwatch\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ .Values.legendFormat_ReceivePod }}"
    },
    {
     "expr": "sum(rate(container_network_transmit_errors_total{namespace=\"amazon-cloudwatch\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ .Values.legendFormat_TransmitPod }}"
    }
   ]
  },
  {
   "title": "network_packets_dropped",
   "type": "timeseries",
   "description": "container_network_transmit_packets_dropped_total / container_network_receive_packets_dropped_total",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total{namespace=\"amazon-cloudwatch\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ .Values.legendFormat_ReceivePod }}"
    },
    {
     "expr": "sum(rate(container_network_transmit_packets_dropped_total{namespace=\"amazon-cloudwatch\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ .Values.legendFormat_TransmitPod }}"
    }
   ]
  },
  {
   "title": "memory_working_set_btyes",
   "type": "timeseries",
   "description": "container_memory_working_set_bytes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"amazon-cloudwatch\"}) by (pod)",
     "legendFormat": "{{ .Values.legendFormat_Pod }}"
    }
   ]
  },
  { "title": "istio-system Namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 } },
  {
   "title": "cpu_usage_seconds",
   "type": "timeseries",
   "description": "container_cpu_usage_seconds_total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"istio-system\",container!=\"\",container!=\"POD\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ .Values.legendFormat_Pod }}"
    }
   ]
  },
  {
   "title": "cpu throttled",
   "type": "timeseries",
   "description": "container_cpu_cfs_throttled_seconds_total",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{namespace=\"istio-system\",container!=\"\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ .Values.legendFormat_Pod }}"
    }
   ]
  },
  {
   "title": "network_receive_bytes",
   "type": "timeseries",
   "description": "container_network_receive_bytes_total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"istio-system\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ .Values.legendFormat_Pod }}"
    }
   ]
  },
  {
   "title": "network_transmit_bytes",
   "type": "timeseries",
   "description": "container_network_transmit_bytes_total",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"istio-system\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ .Values.legendFormat_Pod }}"
    }
   ]
  },
  {
   "title": "network_errors",
   "type": "timeseries",
   "description": "container_network_transmit_errors_total / container_network_receive_errors_total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 140 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_errors_total{namespace=\"istio-system\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ .Values.legendFormat_ReceivePod }}"
    },
    {
     "expr": "sum(rate(container_network_transmit_errors_total{namespace=\"istio-system\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ .Values.legendFormat_TransmitPod }}"
    }
   ]
  },
  {
   "title": "network_packets_dropped",
   "type": "timeseries",
   "description": "container_network_receive_packets_dropped_total / container_network_transmit_packets_dropped_total",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 140 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total{namespace=\"istio-system\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ .Values.legendFormat_ReceivePod }}"
    },
    {
     "expr": "sum(rate(container_network_transmit_packets_dropped_total{namespace=\"istio-system\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ .Values.legendFormat_TransmitPod }}"
    }
   ]
  },
  {
   "title": "memory_working_set_bytes",
   "type": "timeseries",
   "description": "container_memory_working_set_bytes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"istio-system\",name!~\".*POD.*\",name!=\"\",name!~\".*configmap.*\"}) by (pod)",
     "legendFormat": "{{ .Values.legendFormat_Pod }}"
    }
   ]
  }
 ]
}