{
 "title": "Kubernetes Pods (cpu / memory / IO) for Org0 & Org1",
 "description": "Kubernetes Pods (cpu / memory / IO) by Org0 & Org1",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Default Namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "cpu_usage_seconds",
     "type": "timeseries",
     "description": "container_cpu_usage_seconds_total",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"default\",container!=\"\",container!=\"POD\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "cpu throttled",
     "type": "timeseries",
     "description": "container_cpu_cfs_throttled_seconds_total",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{namespace=\"default\",container!=\"\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "fs_writes_bytes",
     "type": "timeseries",
     "description": "container_fs_writes_bytes_total",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{namespace=\"default\",container=~\".+\"}[$__rate_interval])) by (pod,device)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "fs_reads_bytes",
     "type": "timeseries",
     "description": "container_fs_reads_bytes_total",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{namespace=\"default\",container=~\".+\"}[$__rate_interval])) by (pod,device)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "network_receive_bytes",
     "type": "timeseries",
     "description": "container_network_receive_bytes_total",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"default\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "network_transmit_bytes",
     "type": "timeseries",
     "description": "container_network_transmit_bytes_total",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"default\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "network_errors",
     "type": "timeseries",
     "description": "container_network_receive_errors_total / container_network_transmit_errors_total",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_errors_total{namespace=\"default\"}[$__rate_interval])) by (pod)",
       "legendFormat": "rec-{{pod}}"
      },
      {
       "expr": "sum(rate(container_network_transmit_errors_total{namespace=\"default\"}[$__rate_interval])) by (pod)",
       "legendFormat": "tra-{{pod}}"
      }
     ]
    },
    {
     "title": "network_packets_dropped",
     "type": "timeseries",
     "description": "container_network_receive_packets_dropped_total",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_dropped_total{namespace=\"default\"}[$__rate_interval])) by (pod)",
       "legendFormat": "rec-{{pod}}"
      },
      {
       "expr": "sum(rate(container_network_transmit_packets_dropped_total{namespace=\"default\"}[$__rate_interval])) by (pod)",
       "legendFormat": "tra-{{pod}}"
      }
     ]
    },
    {
     "title": "memory_working_set_bytes",
     "type": "timeseries",
     "description": "container_memory_working_set_bytes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"default\",name!~\".*POD.*\",name!=\"\",name!~\".*configmap.*\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "n0 Namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "cpu_usage_seconds",
     "type": "timeseries",
     "description": "container_cpu_usage_seconds_total",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"n0\",container!=\"\",container!=\"POD\",container!=\"enrollment-ca-org0\",container!=\"tls-ca-org0\"}[$__rate_interval])) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "cpu throttled",
     "type": "timeseries",
     "description": "container_cpu_cfs_throttled_seconds_total",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{namespace=\"n0\",container!=\"\",container!=\"tls-ca-org0\",container!=\"enrollment-ca-org0\"}[$__rate_interval])) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "fs_writes_bytes_total",
     "type": "timeseries",
     "description": "container_fs_writes_bytes_total",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{namespace=\"n0\",container=~\".+\",container!~\".*ca-org0.*\"}[$__rate_interval])) by (container,device)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "fs_reads_bytes",
     "type": "timeseries",
     "description": "container_fs_reads_bytes_total",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{namespace=\"n0\",container=~\".+\",container!~\".*ca-org0.*\"}[$__rate_interval])) by (container,device)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "network_receive_bytes",
     "type": "timeseries",
     "description": "container_network_receive_bytes_total",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"n0\",name!~\".*ca-org0.*\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "network_transmit_bytes",
     "type": "timeseries",
     "description": "container_network_transmit_bytes_total",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"n0\",name!~\".*ca-org0.*\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "network_errors",
     "type": "timeseries",
     "description": "container_network_receive_errors_total / container_network_transmit_errors_total",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_errors_total{namespace=\"n0\",name!~\".*ca-org0.*\"}[$__rate_interval])) by (name)",
       "legendFormat": "rec-{{name}}"
      },
      {
       "expr": "sum(rate(container_network_transmit_errors_total{namespace=\"n0\",name!~\".*ca-org0.*\"}[$__rate_interval])) by (name)",
       "legendFormat": "tra-{{name}}"
      }
     ]
    },
    {
     "title": "network_packets_dropped",
     "type": "timeseries",
     "description": "container_network_transmit_packets_dropped_total / container_network_receive_packets_dropped_total",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_dropped_total{namespace=\"n0\",name!~\".*ca-org0.*\"}[$__rate_interval])) by (name)",
       "legendFormat": "rec-{{name}}"
      },
      {
       "expr": "sum(rate(container_network_transmit_packets_dropped_total{namespace=\"n0\",name!~\".*ca-org0.*\"}[$__rate_interval])) by (name)",
       "legendFormat": "tra-{{name}}"
      }
     ]
    },
    {
     "title": "memory_working_set_bytes",
     "type": "timeseries",
     "description": "container_memory_working_set_bytes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"n0\",name!~\".*POD.*\",name!=\"\",name!~\".*ca-org0.*\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "n1 Namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "cpu_usage_seconds",
     "type": "timeseries",
     "description": "container_cpu_usage_seconds_total",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"n1\",container!=\"\",container!=\"POD\",container!=\"tornadoapp-n1\",container!=\"enrollment-ca-org1\",container!=\"tls-ca-org1\",container!~\".*ui-n1.*\"}[$__rate_interval])) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "cpu throttled",
     "type": "timeseries",
     "description": "container_cpu_cfs_throttled_seconds_total",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{namespace=\"n1\",container!=\"\",container!=\"tornadoapp-n1\",container!=\"tls-ca-org1\",container!=\"enrollment-ca-org1\",container!~\".*ui-n1.*\"}[$__rate_interval])) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "fs_writes_bytes",
     "type": "timeseries",
     "description": "container_fs_writes_bytes_total",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{namespace=\"n1\",container=~\".+\",container!~\".*ca-org1.*\"}[$__rate_interval])) by (container,device)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "fs_reads_bytes",
     "type": "timeseries",
     "description": "container_fs_reads_bytes_total",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{namespace=\"n1\",container=~\".+\",container!~\".*ca-org1.*\"}[$__rate_interval])) by (container,device)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "network_receive_bytes",
     "type": "timeseries",
     "description": "container_network_receive_bytes_total",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"n1\",name!~\".*ca-org1.*\",name!~\".*ui-n1.*\",name!~\".*tornado.*\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "network_transmit_bytes",
     "type": "timeseries",
     "description": "container_network_transmit_bytes_total",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"n1\",name!~\".*ca-org1.*\",name!~\".*ui-n1.*\",name!~\".*tornado.*\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "network_errors",
     "type": "timeseries",
     "description": "container_network_receive_errors_total / container_network_transmit_errors_total",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_errors_total{namespace=\"n1\",name!~\".*ca-org1.*\",name!~\".*ui-n1.*\",name!~\".*tornado.*\"}[$__rate_interval])) by (name)",
       "legendFormat": "rec-{{name}}"
      },
      {
       "expr": "sum(rate(container_network_transmit_errors_total{namespace=\"n1\",name!~\".*ca-org1.*\",name!~\".*ui-n1.*\",name!~\".*tornado.*\"}[$__rate_interval])) by (name)",
       "legendFormat": "tra-{{name}}"
      }
     ]
    },
    {
     "title": "network_packets_dropped",
     "type": "timeseries",
     "description": "container_network_receive_packets_dropped_total / container_network_receive_packets_dropped_total",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_dropped_total{namespace=\"n1\",name!~\".*ca-org1.*\",name!~\".*ui-n1.*\",name!~\".*tornado.*\"}[$__rate_interval])) by (name)",
       "legendFormat": "rec-{{name}}"
      },
      {
       "expr": "sum(rate(container_network_receive_packets_dropped_total{namespace=\"n1\",name!~\".*ca-org1.*\",name!~\".*ui-n1.*\",name!~\".*tornado.*\"}[$__rate_interval])) by (name)",
       "legendFormat": "tra-{{name}}"
      }
     ]
    },
    {
     "title": "memory_working_set_bytes",
     "type": "timeseries",
     "description": "container_memory_working_set_bytes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"n1\",name!~\".*POD.*\",name!=\"\",name!~\".*ca-org1.*\",name!~\".*tornado.*\",name!~\".*ui-n1.*\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "istio-system Namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "cpu_usage_seconds",
     "type": "timeseries",
     "description": "container_cpu_usage_seconds_total",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"istio-system\",container!=\"\",container!=\"POD\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "cpu throttled",
     "type": "timeseries",
     "description": "container_cpu_cfs_throttled_seconds_total",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{namespace=\"istio-system\",container!=\"\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "network_receive_bytes",
     "type": "timeseries",
     "description": "container_network_receive_bytes_total",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"istio-system\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "network_transmit_bytes",
     "type": "timeseries",
     "description": "container_network_transmit_bytes_total",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"istio-system\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "network_errors",
     "type": "timeseries",
     "description": "container_network_receive_errors_total / container_network_transmit_errors_total",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 140 },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_errors_total{namespace=\"istio-system\"}[$__rate_interval])) by (pod)",
       "legendFormat": "rec-{{pod}}"
      },
      {
       "expr": "sum(rate(container_network_transmit_errors_total{namespace=\"istio-system\"}[$__rate_interval])) by (pod)",
       "legendFormat": "tra-{{pod}}"
      }
     ]
    },
    {
     "title": "network_packets_dropped",
     "type": "timeseries",
     "description": "container_network_receive_packets_dropped_total / container_network_transmit_packets_dropped_total",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 140 },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_dropped_total{namespace=\"istio-system\"}[$__rate_interval])) by (pod)",
       "legendFormat": "rec-{{pod}}"
      },
      {
       "expr": "sum(rate(container_network_transmit_packets_dropped_total{namespace=\"istio-system\"}[$__rate_interval])) by (pod)",
       "legendFormat": "tra-{{pod}}"
      }
     ]
    },
    {
     "title": "memory_working_set_bytes",
     "type": "timeseries",
     "description": "container_memory_working_set_bytes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 148 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"istio-system\",name!~\".*POD.*\",name!=\"\",name!~\".*configmap.*\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "cloudWatch Namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "cpu_usage_seconds",
     "type": "timeseries",
     "description": "container_cpu_usage_seconds_total",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"amazon-cloudwatch\",container!=\"\",container!=\"POD\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "cpu throttled",
     "type": "timeseries",
     "description": "container_cpu_cfs_throttled_seconds_total",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{namespace=\"amazon-cloudwatch\"}[$__rate_interval])) by (id)",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "fs_writes_bytes",
     "type": "timeseries",
     "description": "container_fs_writes_bytes_total",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{namespace=\"amazon-cloudwatch\",container=~\".+\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "fs_reads_bytes",
     "type": "timeseries",
     "description": "container_fs_reads_bytes_total",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{namespace=\"amazon-cloudwatch\"}[$__rate_interval])) by (id)",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "network_receive_bytes",
     "type": "timeseries",
     "description": "container_network_receive_bytes_total",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"amazon-cloudwatch\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "network_transmit_bytes",
     "type": "timeseries",
     "description": "container_network_transmit_bytes_total",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"amazon-cloudwatch\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "network_errors",
     "type": "timeseries",
     "description": "container_network_receive_errors_total / container_network_transmit_errors_total",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_errors_total{namespace=\"amazon-cloudwatch\"}[$__rate_interval])) by (pod)",
       "legendFormat": "rec-{{pod}}"
      },
      {
       "expr": "sum(rate(container_network_transmit_errors_total{namespace=\"amazon-cloudwatch\"}[$__rate_interval])) by (pod)",
       "legendFormat": "tra-{{pod}}"
      }
     ]
    },
    {
     "title": "network_packets_dropped",
     "type": "timeseries",
     "description": "container_network_receive_packets_dropped_total / container_network_transmit_packets_dropped_total",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_dropped_total{namespace=\"amazon-cloudwatch\"}[$__rate_interval])) by (pod)",
       "legendFormat": "rec-{{pod}}"
      },
      {
       "expr": "sum(rate(container_network_transmit_packets_dropped_total{namespace=\"amazon-cloudwatch\"}[$__rate_interval])) by (pod)",
       "legendFormat": "tra-{{pod}}"
      }
     ]
    },
    {
     "title": "memory_working_set_bytes",
     "type": "timeseries",
     "description": "container_memory_working_set_bytes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"amazon-cloudwatch\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}