{
 "title": "Hyperledger Fabric Monitoring",
 "description": "A beta version of the HLF Monitoring Dashboard.",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Hyperledger Fabric Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Fabric Version",
   "type": "gauge",
   "description": "fabric_version",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "fabric_version{job=\"hyperledger-peer0\"}"
    }
   ]
  },
  {
   "title": "Height of Chain (P0)",
   "type": "gauge",
   "description": "ledger_blockchain_height",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ledger_blockchain_height{job=\"hyperledger-peer0\"}"
    }
   ]
  },
  {
   "title": "Incomplete deliver_request (P0)",
   "type": "timeseries",
   "description": "deliver_requests_received- deliver_requests_completed",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "deliver_requests_received{job=\"hyperledger-peer0\",data_type=\"block\", filtered=\"false\"}",
     "legendFormat": " received"
    },
    {
     "expr": "deliver_requests_completed{job=\"hyperledger-peer0\",data_type=\"block\", filtered=\"false\"}",
     "legendFormat": "completed"
    }
   ]
  },
  {
   "title": "ledger_blockchain_height (P0)",
   "type": "timeseries",
   "description": "Height of the chain in blocks. ",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ledger_blockchain_height{job=\"hyperledger-peer0\"}[1d]",
     "legendFormat": "peer0"
    }
   ]
  },
  {
   "title": "ledger_statedb_commit_time_count",
   "type": "timeseries",
   "description": "ledger_statedb_commit_time_count",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "ledger_statedb_commit_time_count{job=\"hyperledger-peer0\"}"
    }
   ]
  },
  {
   "title": "ledger_transaction_count (P0)",
   "type": "timeseries",
   "description": "Number of transactions processed.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ledger_transaction_count{chaincode=\"eventstore:1.0\",job=\"hyperledger-peer0\"}[$__range]"
    }
   ]
  },
  {
   "title": "Chaincode Shim Requests (P0)",
   "type": "graph",
   "description": "chaincode_shim_requests_received / completed",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(chaincode_shim_requests_received{job=\"hyperledger-peer0\"}[5m])",
     "legendFormat": "{{channel}}, {{chaincode}}, {{type}}"
    },
    {
     "expr": "rate(chaincode_shim_requests_completed{job=\"hyperledger-peer0\"}[5m])",
     "legendFormat": "{{channel}}, {{chaincode}}, {{type}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(chaincode_shim_request_duration_bucket{job=\"hyperledger-peer0\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "ledger_block_processing_time_count (P0)",
   "type": "timeseries",
   "description": "Time taken in seconds for ledger block processing.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ledger_block_processing_time_count{job=\"hyperledger-peer0\"}[$__interval])",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "chaincode_launch_failures",
   "type": "gauge",
   "description": "chaincode_launch_failures",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chaincode_launch_failures" }
   ]
  },
  {
   "title": "chaincode_execute_timeouts",
   "type": "gauge",
   "description": "chaincode_execute_timeouts",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chaincode_execute_timeouts", "legendFormat": "CouchDB" }
   ]
  },
  {
   "title": "gRPC Connections",
   "type": "graph",
   "description": "rate(grpc_comm_conn_closed[5m])",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(grpc_comm_conn_closed{job=\"hyperledger-peer0\"}[$__rate_interval])",
     "legendFormat": "closed-p0"
    },
    {
     "expr": "irate(grpc_comm_conn_closed{job=\"hyperledger-peer1\"}[$__rate_interval])",
     "legendFormat": "closed-p1"
    },
    {
     "expr": "irate(grpc_comm_conn_opened{job=\"hyperledger-peer0\"}[$__rate_interval])",
     "legendFormat": "opened-p0"
    },
    {
     "expr": "irate(grpc_comm_conn_opened{job=\"hyperledger-peer1\"}[$__rate_interval])",
     "legendFormat": "opened-p1"
    }
   ]
  },
  { "title": "grpc (P0)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "grpc_server_unary_request_duration / Proposal (P0)",
   "type": "timeseries",
   "description": "grpc_server_unary_request_duration_count",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(grpc_server_unary_request_duration_sum{job=\"hyperledger-peer0\",method=\"ProcessProposal\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "grpc_server_unary_request_duration / Proposal (P0)",
   "type": "histogram",
   "description": "grpc_server_unary_request_duration_bucket",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_server_unary_request_duration_bucket{job=\"hyperledger-peer0\",method=\"ProcessProposal\"}[$__range])) by (le))"
    }
   ]
  },
  { "title": "Endorser (P0)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "cc instantiation failures",
   "type": "gauge",
   "description": "endorser_chaincode_instantiation_failures",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "endorser_chaincode_instantiation_failures"
    }
   ]
  },
  {
   "title": "duplicate TX failures",
   "type": "gauge",
   "description": "endorser_duplicate_transaction_failures",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "endorser_duplicate_transaction_failures"
    }
   ]
  },
  {
   "title": "endorsement failures",
   "type": "gauge",
   "description": "endorser_endorsement_failures",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "endorser_endorsement_failures" }
   ]
  },
  {
   "title": "proposal simulation failures",
   "type": "gauge",
   "description": "endorser_proposal_simulation_failures",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "endorser_proposal_simulation_failures"
    }
   ]
  },
  {
   "title": "prop validation failures",
   "type": "gauge",
   "description": "endorser_proposal_validation_failures",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "endorser_proposal_validation_failures"
    }
   ]
  },
  {
   "title": "proposals succeed vs received (P0)",
   "type": "timeseries",
   "description": "endorser_successful_proposals",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 26 },
   "targets": [
    {
     "expr": "endorser_successful_proposals{job=\"hyperledger-peer0\"}",
     "legendFormat": "succeed"
    },
    {
     "expr": "endorser_proposals_received{job=\"hyperledger-peer0\"}",
     "legendFormat": "received"
    }
   ]
  },
  { "title": "Gossip (P0)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "leader election (P0)",
   "type": "gauge",
   "description": "gossip_leader_election_leader",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gossip_leader_election_leader{job=\"hyperledger-peer0\"}"
    }
   ]
  },
  {
   "title": "Total peers known (P0)",
   "type": "gauge",
   "description": "gossip_membership_total_peers_known",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gossip_membership_total_peers_known{job=\"hyperledger-peer0\"}"
    }
   ]
  },
  {
   "title": "gossip_state_height (P0)",
   "type": "gauge",
   "description": "gossip_state_height",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gossip_state_height{job=\"hyperledger-peer0\"}"
    }
   ]
  },
  {
   "title": "messages",
   "type": "timeseries",
   "description": "gossip_comm_messages_received / gossip_comm_messages_sent",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "irate(gossip_comm_messages_received{job=\"hyperledger-peer0\"}[$__rate_interval])",
     "legendFormat": "received-p0"
    },
    {
     "expr": "irate(gossip_comm_messages_received{job=\"hyperledger-peer1\"}[$__rate_interval])",
     "legendFormat": "received-p1"
    },
    {
     "expr": "irate(gossip_comm_messages_sent{job=\"hyperledger-peer0\"}[$__rate_interval])",
     "legendFormat": "send-p0"
    },
    {
     "expr": "irate(gossip_comm_messages_sent{job=\"hyperledger-peer1\"}[$__rate_interval])",
     "legendFormat": "sent-p1"
    },
    {
     "expr": "irate(gossip_comm_overflow_count[$__interval])",
     "legendFormat": "overflow"
    }
   ]
  },
  { "title": "Go Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Go Memory Allocations",
   "type": "graph",
   "description": "go_memstats_alloc_bytes",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job!=\"kubernetes-service-endpoints\",job!=\"kubernetes-apiservers\",job!=\"kubernetes-nodes\",job!=\"kubernetes-pods\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Go Heap Objects",
   "type": "graph",
   "description": "go_memstats_alloc_bytes",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_heap_objects{job!=\"prometheus\",job!=\"kubernetes-apiservers\",job!=\"kubernetes-service-endpoints\",job!=\"kubernetes-pods\",job!=\"kubernetes-nodes\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Go Garbage Collection",
   "type": "timeseries",
   "description": "go_gc_duration_seconds",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds{job!=\"kubernetes-service-endpoints\",job!=\"kubernetes-apiservers\",job!=\"kubernetes-pods\",job!=\"kubernetes-nodes\",job!=\"prometheus\"}[5m])",
     "legendFormat": "{{instance}}/{{job}}"
    }
   ]
  },
  {
   "title": "Go Free Memory",
   "type": "timeseries",
   "description": "go_gc_duration_seconds",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_memstats_frees_total{job!=\"kubernetes-service-endpoints\",job!=\"kubernetes-apiservers\",job!=\"kubernetes-nodes\"}[5m])",
     "legendFormat": "{{instance}}/{{job}}"
    }
   ]
  }
 ]
}