{
 "title": "Orderers",
 "description": "Hyperledger Orderers Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "cluster msg dropped",
   "type": "gauge",
   "description": "cluster_comm_msg_dropped_count",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cluster_comm_msg_dropped_count" }
   ]
  },
  {
   "title": "Leader",
   "type": "bargauge",
   "description": "consensus_etcdraft_is_leader",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "consensus_etcdraft_is_leader{channel!=\"ordererchannel\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "consensus_etcdraft_active_nodes",
   "type": "bargauge",
   "description": "consensus_etcdraft_active_nodes",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "consensus_etcdraft_active_nodes{channel!=\"ordererchannel\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "ledger_blockchain_height",
   "type": "bargauge",
   "description": "ledger_blockchain_height",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ledger_blockchain_height{channel!=\"ordererchannel\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "blockcutter_block_fill_duration_count",
   "type": "timeseries",
   "description": "blockcutter_block_fill_duration_count",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "blockcutter_block_fill_duration_count",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "config proposals received",
   "type": "gauge",
   "description": "consensus_etcdraft_config_proposals_received",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "consensus_etcdraft_config_proposals_received{job=\"hyperledger-orderer0\",channel!=\"ordererchannel\"}"
    }
   ]
  },
  {
   "title": "ledger_blockstorage_commit_time_bucket",
   "type": "histogram",
   "description": "ledger_blockstorage_commit_time_bucket",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(ledger_blockstorage_commit_time_bucket[$__range])))"
    }
   ]
  },
  {
   "title": "cluster_comm_egress_queue_length (orderer0)",
   "type": "timeseries",
   "description": "cluster_comm_egress_queue_length",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "cluster_comm_egress_queue_length{channel!=\"ordererchannel\",msg_type=\"consensus\",host=\"orderer0-org0.cdi.testnet:7050\"}",
     "legendFormat": "{{job}},{{msg_type}}"
    }
   ]
  },
  { "title": "Deliver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "deliver_blocks_sent",
   "type": "timeseries",
   "description": "deliver_blocks_sent",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(deliver_blocks_sent[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "deliver_streams_opened",
   "type": "timeseries",
   "description": "deliver_streams_opened",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "rate(deliver_streams_opened[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "deliver_requests_received",
   "type": "timeseries",
   "description": "deliver_requests_received",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "rate(deliver_requests_received[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "deliver_streams_closed",
   "type": "timeseries",
   "description": "deliver_streams_closed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "rate(deliver_streams_closed[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "deliver_requests_completed",
   "type": "timeseries",
   "description": "deliver_requests_completed",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "rate(deliver_requests_completed[$__rate_interval])",
     "legendFormat": "{{job}}-{{success}}"
    }
   ]
  },
  { "title": "Consensus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "consensus_etcdraft_proposal_failures",
   "type": "timeseries",
   "description": "consensus_etcdraft_proposal_failures",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "consensus_etcdraft_proposal_failures",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "consensus_etcdraft_normal_proposals_received",
   "type": "timeseries",
   "description": "consensus_etcdraft_normal_proposals_received",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "consensus_etcdraft_normal_proposals_received",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "consensus_etcdraft_committed_block_number",
   "type": "timeseries",
   "description": "consensus_etcdraft_committed_block_number",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "consensus_etcdraft_committed_block_number{channel!=\"ordererchannel\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "consensus_etcdraft_data_persist_duration_count",
   "type": "timeseries",
   "description": "consensus_etcdraft_data_persist_duration_count",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "rate(consensus_etcdraft_data_persist_duration_count{channel!=\"ordererchannel\"}[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Broadcast", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "broadcast_processed_count / SUCCESS",
   "type": "timeseries",
   "description": "broadcast_processed_count",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "broadcast_processed_count{type=\"ENDORSER_TRANSACTION\",status=\"SUCCESS\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "broadcast_processed_count / UNAVAILABLE",
   "type": "timeseries",
   "description": "broadcast_processed_count",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "broadcast_processed_count{type=\"ENDORSER_TRANSACTION\",status=\"SERVICE_UNAVAILABLE\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "broadcast_enqueue_duration_count",
   "type": "timeseries",
   "description": "broadcast_enqueue_duration_count",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(broadcast_enqueue_duration_count{type=\"ENDORSER_TRANSACTION\",status=\"SUCCESS\"}[$__rate_interval])",
     "legendFormat": "success-{{job}}"
    },
    {
     "expr": "rate(broadcast_enqueue_duration_count{type=\"ENDORSER_TRANSACTION\",status=\"SERVICE_UNAVAILABLE\"}[$__rate_interval])",
     "legendFormat": "unavailable-{{job}}"
    }
   ]
  },
  {
   "title": "broadcast_validate_duration_count",
   "type": "timeseries",
   "description": "broadcast_validate_duration_count",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(broadcast_validate_duration_count{type=\"ENDORSER_TRANSACTION\", status=\"SUCCESS\"}[$__rate_interval])",
     "legendFormat": "success-{{job}}"
    },
    {
     "expr": "rate(broadcast_validate_duration_count{type=\"ENDORSER_TRANSACTION\", status=\"SERVICE_UNAVAILABLE\"}[$__rate_interval])",
     "legendFormat": "unavailable-{{job}}"
    }
   ]
  }
 ]
}