{
 "title": "redisearch",
 "description": "redisearch exporter",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "Commit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "num_docs / cidx",
   "type": "gauge",
   "description": "redisearch_num_docs",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redisearch_num_docs{job=\"redis_exporter_targets\",idx=\"cidx\"}"
    }
   ]
  },
  {
   "title": "num_records / cidx",
   "type": "gauge",
   "description": "redisearch_num_records",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redisearch_num_records{job=\"redis_exporter_targets\",idx=\"cidx\"}"
    }
   ]
  },
  {
   "title": "num_terms / cidx",
   "type": "gauge",
   "description": "redisearch_num_terms",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redisearch_num_terms{job=\"redis_exporter_targets\",idx=\"cidx\"}"
    }
   ]
  },
  {
   "title": "max_doc_id  / cidx",
   "type": "gauge",
   "description": "redisearch_max_doc_id",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redisearch_max_doc_id{job=\"redis_exporter_targets\",idx=\"cidx\"}"
    }
   ]
  },
  {
   "title": "num_docs / cidx",
   "type": "timeseries",
   "description": "redisearch_num_docs",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "redisearch_num_docs{job=\"redis_exporter_targets\",idx=\"cidx\"}",
     "legendFormat": "num_docs"
    }
   ]
  },
  { "title": "DataRequest", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "num_docs / DataRequest",
   "type": "gauge",
   "description": "redisearch_num_docs",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redisearch_num_docs{job=\"redis_exporter_targets\",idx=\"eidx:DataRequest\"}"
    }
   ]
  },
  {
   "title": "num_records / DataRequest",
   "type": "gauge",
   "description": "redisearch_num_records",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redisearch_num_records{job=\"redis_exporter_targets\",idx=\"eidx:DataRequest\"}"
    }
   ]
  },
  {
   "title": "num_terms / DataRequest",
   "type": "gauge",
   "description": "redisearch_num_terms",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redisearch_num_terms{job=\"redis_exporter_targets\",idx=\"eidx:DataRequest\"}"
    }
   ]
  },
  {
   "title": "max_doc_id / DataRequest",
   "type": "gauge",
   "description": "redisearch_max_doc_id",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redisearch_max_doc_id{job=\"redis_exporter_targets\",idx=\"eidx:DataRequest\"}"
    }
   ]
  },
  {
   "title": "num_docs / DataRequest",
   "type": "timeseries",
   "description": "redisearch_num_docs",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "redisearch_num_docs{job=\"redis_exporter_targets\",idx=\"eidx:DataRequest\"}"
    }
   ]
  },
  { "title": "Consent", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "num_docs / Consent",
   "type": "gauge",
   "description": "redisearch_num_docs",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redisearch_num_docs{job=\"redis_exporter_targets\",idx=\"eidx:Consent\"}"
    }
   ]
  },
  {
   "title": "num_records / Consent",
   "type": "gauge",
   "description": "redisearch_num_records",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redisearch_num_records{job=\"redis_exporter_targets\",idx=\"eidx:Consent\"}"
    }
   ]
  },
  {
   "title": "num_terms / Consent",
   "type": "gauge",
   "description": "redisearch_num_terms",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redisearch_num_terms{job=\"redis_exporter_targets\",idx=\"eidx:Consent\"}"
    }
   ]
  },
  {
   "title": "max_doc_id / Consent",
   "type": "gauge",
   "description": "redisearch_max_doc_id",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redisearch_max_doc_id{job=\"redis_exporter_targets\",idx=\"eidx:Consent\"}"
    }
   ]
  },
  {
   "title": "num_docs / Consent",
   "type": "timeseries",
   "description": "redisearch_num_docs",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "redisearch_num_docs{job=\"redis_exporter_targets\",idx=\"eidx:Consent\"}"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "redisearch_bytes_per_record_avg",
   "type": "timeseries",
   "description": "redisearch_bytes_per_record_avg",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "redisearch_bytes_per_record_avg{job=\"redis_exporter_targets\",idx!=\"eidx:organization\",idx!=\"eidx:participantDs\",idx!=\"eidx:user\"}"
    }
   ]
  },
  {
   "title": "redisearch_doc_table_size_bytes",
   "type": "timeseries",
   "description": "redisearch_doc_table_size_bytes",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redisearch_doc_table_size_bytes{job=\"redis_exporter_targets\",idx!=\"eidx:user\",idx!=\"eidx:organization\",idx!=\"eidx:participantDs\"}"
    }
   ]
  },
  {
   "title": "redisearch_key_table_size_bytes",
   "type": "timeseries",
   "description": "redisearch_key_table_size_bytes",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redisearch_key_table_size_bytes{job=\"redis_exporter_targets\",idx!=\"eidx:participantDs\",idx!=\"eidx:user\",idx!=\"eidx:organization\"}"
    }
   ]
  }
 ]
}